# Generated by Django 5.2.1 on 2025-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_is_exchanged_alter_ad_category_alter_ad_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_exchanged',
            field=models.BooleanField(default=False, verbose_name='Обмен завершён'),
        ),
    ]
