# Generated by Django 5.2.1 on 2025-05-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_is_exchanged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_exchanged',
            field=models.BooleanField(default=False, verbose_name='Состояние обмена'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='Получаемый товар'),
        ),
    ]
